# Apple ISO French (Macintosh). Skip this file if your legends are not Mac AZERTY.
KEYMAP=mac-fr
XKBLAYOUT=fr
XKBMODEL=pc105
XKBVARIANT=mac
XKBOPTIONS=compose:caps,shift:both_capslock_cancel
FONT=default8x16
